Add guidance on when to have multiple suppliers per award
open-contracting/standard pull request #1115
Opened 2020-11-11 18:59 UTC by yolile

closes #912

2020-11-11 19:45 UTC, yolile commented
@duncandewhurst this is ready to review but I will include the link to the framework example too when #1106 is merged

2020-11-26 02:22 UTC, duncandewhurst requested changes

2020-11-26 02:22 UTC, duncandewhurst commented on schema/release-schema.json
> +          "description": "The suppliers awarded this award. If different suppliers have been awarded different items or values, these should be split into separate award blocks. There can be multiple
Aligning with the language in the frameworks example:
```suggestion
          "description": "The suppliers awarded this award. If different suppliers have been awarded different items or values, these should be split into separate award blocks. There can be multiple suppliers for a single award if, for example, the award recipient is an unincorporated consortium or if the award represents the addition of suppliers as parties to a framework agreement.",
```

2020-12-18 15:08 UTC, jpmckinney commented
@yolile Is this still draft?

2020-12-18 15:11 UTC, yolile commented
@jpmckinney this depends on #1123 to add the link to the new FA documentation

2020-12-18 17:50 UTC, jpmckinney commented
I think we can merge this first, and just add the link in #1123.

2020-12-23 01:54 UTC, duncandewhurst approved these changes

2021-01-05 12:52 UTC, merged