release-schema: add Value.date field
open-contracting/standard pull request #1331
Opened 2021-07-14 15:47 UTC by yolile

closes #988

2021-07-14 23:50 UTC, duncandewhurst requested changes
Did you consider expanding the description based on https://en.wikipedia.org/wiki/Value_date?

2021-07-14 23:50 UTC, duncandewhurst commented on schema/release-schema.json
> +          "description": "The date when the value is set. The value date is used when analysing historical values due to inflation over time.",
"when" -> "on which", for consistency with the descriptions of other date fields.

I think the usage example from the issue description is clearer:

```suggestion
          "description": "The date on which the value is set. The value date is useful to correctly sum values over longer periods of time, especially in contexts with high inflation.",
```

2021-07-15 14:49 UTC, yolile commented
> Did you consider expanding the description based on https://en.wikipedia.org/wiki/Value_date?

Yes, but I'm sure if "assets" is a concept that we want to introduce?

2021-07-15 21:22 UTC, duncandewhurst approved these changes

2021-07-15 21:25 UTC, duncandewhurst commented
> > Did you consider expanding the description based on https://en.wikipedia.org/wiki/Value_date?
> 
> Yes, but I'm sure if "assets" is a concept that we want to introduce?

Probably not, since `Value` can be used in many different contexts in OCDS. I think the description is clear enough as it is.

2021-07-16 19:36 UTC, jpmckinney commented
"is set" can be confused with "when we agreed this was worth $100", which might be at a very different time than "when we traded $100 for goods". This led me to more comments in #988. Closing per comment there.

2021-07-16 19:36 UTC, closed without merging