add omitWhenMerged=true to publisher field in release-schema
open-contracting/standard pull request #1489
Opened 2022-03-15 14:49 UTC by odscjen

adding omitWhenMerged = true to release schema for 1.2 as discussed in #1483

2022-03-15 19:56 UTC, duncandewhurst requested changes
The schema changes look good. Please can you update the [changelog](https://github.com/open-contracting/standard/blob/1483-publisher-omitWhenMerged/docs/history/changelog.md).

FYI - you don't need to set labels on PRs, we only use those for categorising issues. Also, if you [use a keyword to link a PR to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) it will automatically close the issue once the PR is merged, e.g. Closes #1483

2022-03-16 09:33 UTC, odscjen commented
Great, I'll do that. Can I just check how the changelog works, am I right in assuming that I'd be adding a line explaining this under the section [1.2] - YYY-MM-DD / schema / clarifying merging behavior? And that I'd add it to the bottom of that section?

2022-03-17 01:50 UTC, duncandewhurst commented
Since this is just fixing an omission in a field that is added in the same release, I think it's fine just to update https://github.com/open-contracting/standard/blob/686e1b7229f9c68c5cc8ff7a689f59278941346b/docs/history/changelog.md?plain=1#L170 to read:

```markdown
* [#1376](https://github.com/open-contracting/standard/pull/1376), [#1489](https://github.com/open-contracting/standard/pull/1489) `publisher`
```

2022-03-22 21:40 UTC, duncandewhurst approved these changes

2022-03-28 20:15 UTC, jpmckinney commented on docs/history/changelog.md
> +  * [#1376](https://github.com/open-contracting/standard/pull/1376),[#1489](https://github.com/open-contracting/standard/pull/1489) `publisher`
```suggestion
  * [#1376](https://github.com/open-contracting/standard/pull/1376), [#1489](https://github.com/open-contracting/standard/pull/1489) `publisher`
```

2022-03-28 20:15 UTC, jpmckinney approved these changes

2022-03-29 02:55 UTC, merged