add awards.datePublished field
open-contracting/standard pull request #1492
Opened 2022-03-29 15:46 UTC by odscjen

adding awards.datePublished field to close issue #1456

2022-03-29 23:13 UTC, duncandewhurst requested changes

2022-03-29 23:13 UTC, duncandewhurst commented on schema/release-schema.json
> +          "description": "The date that the award was published.",
For consistency with `tender.datePublished`:

```suggestion
          "description": "The date on which the award was published.",
```

2022-03-29 23:15 UTC, duncandewhurst commented
Happy for you to request a review from @jpmckinney once you commit my suggestion.

2022-03-30 17:36 UTC, jpmckinney approved these changes

2022-03-30 17:37 UTC, merged