adding amountNet and amountGross to value, updating value definition
open-contracting/standard pull request #1519
Opened 2022-05-18 09:34 UTC by odscjen

closes #817

2022-05-18 10:13 UTC, mrshll1001 requested changes
One very minor change in the form of a typo, otherwise what I'd expect based on the issue,.

2022-05-18 10:13 UTC, mrshll1001 commented on docs/history/changelog.md
> +  * [#1519](https://github.com/open-contracting/standard/pull/1519) `value.amount`, to clarify amount from tender/award/contract notcie document.
Typo on line 204: notcie (notice)

2022-05-18 10:17 UTC, odscjen commented on docs/history/changelog.md
> +  * [#1519](https://github.com/open-contracting/standard/pull/1519) `value.amount`, to clarify amount from tender/award/contract notcie document.
thanks, corrected that now

2022-05-18 11:59 UTC, mrshll1001 approved these changes
This looks fine, typo amended.

2022-07-29 03:17 UTC, jpmckinney reviewed
We can omit "as a number" as this is repetitive with the `type` validation keyword.

I know "The amount as stated in the tender notice / award notice / contract notice document as a number" is the text I suggested in https://github.com/open-contracting/standard/issues/817#issuecomment-542353977, but `Value` objects can appear in many different places, and the numbers might not originate in these specific documents in those cases. The number might also originate from an electronic system, such that there is no "document" per say. 

Unfortunately, as an alternative, I don't think we can use turns of phrase like "original" / "unadjusted" / "unmodified" amount or similar, as we do allow the `amount` of `Value` objects to change over time, and it might just confuse readers as to the semantics.

Maybe something like "The amount as entered into a system or as published in a document."

This PR should also be supported by changes to the Markdown page for the Value object, to explain how the three fields ought to be used/interpreted (e.g. there are three fields so that, when it is unknown whether taxes are included or not, it can nonetheless be entered into `amount` – please be more eloquent than me :)).

The Markdown page should encourage publishers to describe their semantics for `amount`, e.g. a publish that has access to the `amountNet` and `amountGross` can have a policy of entering the `amountNet` in the `amount`. (We can perhaps also encourage this approach of using `amount` for `amountNet` when all are available, for consistency across datasets.)

2022-08-02 19:41 UTC, jpmckinney commented on docs/schema/reference.md
> +* When it is unknown if the value includes all taxes or not use `value/amount`.
The original change doesn't cover all the scenarios discussed in #817. Most of the text was just repeating the semantics of the fields, which doesn't demand repetition.

````suggestion
`currency`, `amountNet` and `amountGross` should be provided, wherever possible.

`amount` is defined as:

```{field-description} ../../build/current_lang/release-schema.json /definitions/Value/properties/amount
```

If both the `amountNet` and the `amountGross` match this definition, enter the `amountNet` as the `amount`.
````

2022-08-02 19:45 UTC, jpmckinney commented on docs/history/changelog.md
> +  * [#1519](https://github.com/open-contracting/standard/pull/1519) `amountNet` and `amountGross` to `value`
```suggestion
  * [#1519](https://github.com/open-contracting/standard/pull/1519) `Value.amountNet` and `Value.amountGross`
```

2023-09-11 13:31 UTC, odscjen commented
@jpmckinney I think all the requested changes to this PR were made so just bumping back for your final review

2023-10-17 04:49 UTC, jpmckinney approved these changes

2023-10-17 04:49 UTC, merged

2023-10-17 04:50 UTC, jpmckinney commented
Not sure why I left this PR open so long. I think I had paused my work on OCDS 1.2 around the time the updates were made.