Add planning final status fields and codelist
open-contracting/standard pull request #1642
Opened 2023-10-09 01:30 UTC by duncandewhurst

* Closes #1583 
* Closes #1582

2023-10-09 01:34 UTC, duncandewhurst commented
The spell-check failure is addressed by https://github.com/open-contracting/standard/pull/1641

2023-10-09 14:11 UTC, odscjen requested changes
My reading of https://github.com/open-contracting/standard/issues/1582 and the associated CRM issue is that it's not just the planning final status date that's needed by also a `tender.finalStatusDate`

2023-10-09 14:11 UTC, odscjen commented on schema/codelists/planningFinalStatus.csv
> +cancelled,Cancelled,"The planning process was cancelled and did not yeild a contracting process. For example, a buyer did not go ahead with planned consultations about the construction of a new recre
```suggestion
cancelled,Cancelled,"The planning process was cancelled and did not yield a contracting process. For example, a buyer did not go ahead with planned consultations about the construction of a new recreational facility and decided not to build the facility."
```

2023-10-09 14:11 UTC, odscjen commented on schema/release-schema.json
> +          "description": "The final status of the planning process, from the closed [planningFinalStatus](https://standard.open-contracting.org/{{version}}/{{lang}}/schema/codelists/#planning-final-s
```suggestion
          "description": "The final status of the planning process, using the closed [planningFinalStatus](https://standard.open-contracting.org/{{version}}/{{lang}}/schema/codelists/#planning-final-status) codelist.",
```

as per the style guide

2023-10-09 19:16 UTC, duncandewhurst commented
Ah, good spot. I shouldn't have marked #1582 as being closed by this PR. I figure it makes sense to do those other final status date fields when adding the new final status fields in #1160.

Alternatively, we could do all of the final status and final status date fields in this PR. @jpmckinney let me know what you prefer.

2023-10-11 04:30 UTC, jpmckinney commented
My comment in #1583 was to close it "After https://github.com/open-contracting/standard/issues/1160 and https://github.com/open-contracting/standard/issues/1582". #1583 is more like a new feature, whereas #1160 is a major change (#1582 is also more like a new feature). The major change should lead, before related features are implemented.

I prefer to close #1160 on its own. #1582 and #1583 could potentially be combined.

2023-10-11 20:35 UTC, duncandewhurst commented
Sounds good! I'll pause work on this PR and prepare a PR for #1160

2024-03-25 03:14 UTC, jpmckinney commented
@duncandewhurst This is now unblocked.

2024-03-28 00:50 UTC, duncandewhurst commented
I think this is ready for review, unless I missed something.

2024-05-04 03:39 UTC, jpmckinney approved these changes
I aligned 'cancelled' with all other 'cancelled' in other codelists (basically, it's a decision by the buyer, always for the same potential reasons).

I also aligned 'unsuccesful' in terms of structure, and using a less specific example. A specific example, is e.g. a building application where residents might reject it.

2024-05-07 08:52 UTC, odscjen approved these changes

2024-05-07 13:46 UTC, merged