release_schema: add organization/details/classifications
open-contracting/standard pull request #1679
Opened 2024-02-28 11:39 UTC by odscjen

addresses #1622 

once this is merged need to address the changes to the extension as per https://github.com/open-contracting/standard/issues/1622#issuecomment-1581756030

2024-03-03 23:17 UTC, duncandewhurst reviewed
Should the additions to the `itemClassificationScheme` codelist also be merged?

2024-03-03 23:17 UTC, duncandewhurst commented on docs/history/changelog.md
> +  * [#1679](https://github.com/open-contracting/standard/pull/1679) `Organization.details.classifications` merged from Organization classifications extension
The changelog doesn't mention the other extensions from which fields were merged (submission terms and pagination).

```suggestion
  * [#1679](https://github.com/open-contracting/standard/pull/1679) `Organization.details.classifications`
```

2024-03-07 10:16 UTC, odscjen commented
> Should the additions to the itemClassificationScheme codelist also be merged?

I had initially thought no because they're all in the 1.1 extension branch too, but now I realise you're right, I'll move them over

2024-03-07 20:57 UTC, duncandewhurst requested changes
Happy for you to request a review from James once the changelog comment is addressed.

2024-03-07 20:57 UTC, duncandewhurst commented on docs/history/changelog.md
> +    * 'eu-main-activity'
Suggest combining with the existing changelog entry for PR #1218

2024-03-07 21:54 UTC, jpmckinney commented on schema/release-schema.json
> +              "description": "The classifications that categorize the organization",
```suggestion
              "description": "The classifications that categorize the organization.",
```

2024-03-08 21:58 UTC, jpmckinney approved these changes

2024-03-08 21:59 UTC, merged